routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/compilations', 'CompilationsController');

Route::post('/compilations/{compilation}/votes', 'CompilationsController@storeVote')
    ->name('compilations.storeVote');

Route::put('/compilations/{compilation}/settings', 'CompilationsController@storeSettings')
    ->name('compilations.storeSettings');

Route::resource('/users', 'UsersController');
Route::get('/users/{user}/compilations', 'CompilationsController@showUserCompilations')
    ->name('compilations.showUserCompilations');

app/Compilation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Compilation extends Model
{
    protected $fillable = ['title', 'description', 'video_id'];

    static function determineSource(Request $request) {
        $source = $request->query('source');
        switch ($source) {
            case 'text': break;
            default:
                $source = 'file';
        }
        return $source;

    }

    public function voters() {
        return $this->belongsToMany(User::class, 'compilation_likes')->withTimestamps();
    }

    public function items() {
        return $this->hasMany(Item::class);
    }

    public function creator() {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function settings() {
        return $this->hasMany(CompilationSettings::class);
    }
}

app/Http/Controllers/CompilationsController.php
<?php

namespace App\Http\Controllers;

use App\Compilation;
use App\CompilationLike;

use App\User;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response as SymfonyResponse;

class CompilationsController extends Controller
{
    /**
     * @var Compilation
     */
    protected $compilation;

    /**
     * @var CompilationLike
     */
    protected $compilationLike;

    public function __construct(Compilation $compilation, CompilationLike $compilationLike)
    {
        $this->compilation         = $compilation;
        $this->compilationLike     = $compilationLike;

        $this->middleware('auth')->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $compilations = $this->compilation->all();

        return view('compilations.index', compact('compilations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $source = Compilation::determineSource($request);

        return view('compilations.create', compact('source'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $compilation = $request->user()->compilations()->create([
            'title'       => $request->get('title'),
            'description' => $request->get('description'),
            'video_id'    => parse_url_and_query($request->get('youtube_url'))['query']['v']
        ]);

        $playlist = $request->get('source') === 'text' ? $request->get('playlist') : file_get_contents($request->file('playlist')->getRealPath());
        $playlist = explode(PHP_EOL, trim($playlist));

        foreach ($playlist as $song) {
            list($time, $artist, $title) = explode('-', $song);
            $compilation->items()->create([
                'artist'         => trim($artist),
                'title'          => trim($title),
                'starts_at_text' => trim($time),
                'starts_at_secs' => textToSecs(trim($time))
            ]);
        }

        return redirect()->route('compilations.show', ['id' => $compilation->id])
            ->with('status', 'New compilation successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param Compilation $compilation
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function show(Compilation $compilation, Request $request)
    {
        $likes = $this->compilationLike->where([
            'vote'           => true,
            'compilation_id' => $compilation->id
        ])->count();

        $dislikes = $this->compilationLike->where([
            'vote'           => false,
            'compilation_id' => $compilation->id
        ])->count();

        $settings = $compilation->settings()
            ->where('user_id', $request->user()->id)
            ->pluck('value', 'id');

        try {
            $vote = (bool) $this->compilationLike->where([
                'compilation_id' => $compilation->id,
                'user_id'        => $request->user()->id
            ])->firstOrFail()->vote;
        } catch (\Exception $e) {
            $vote = null;
        }
        return view('compilations.show', compact('compilation', 'likes', 'dislikes', 'vote', 'settings'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Compilation  $compilation
     * @return \Illuminate\Http\Response
     */
    public function edit(Compilation $compilation)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Compilation  $compilation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Compilation $compilation)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Compilation  $compilation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Compilation $compilation)
    {
        //
    }

    public function storeVote(int $compilationId, Request $request)
    {
        $vote   = $request->post('vote');
        $userId = $request->user()->id;

        $data = [
            'compilation_id' => $compilationId,
            'user_id'        => $userId,
            'vote'           => $vote
        ];

        $deletedRows = $this->compilationLike->where($data)->delete();

        if ($deletedRows != 0) {
            return back()->with('status', 'Vote removed');
        }

        $compilationLike = $this->compilationLike->updateOrCreate([
            'compilation_id' => $compilationId,
            'user_id'        => $userId
        ], [
            'vote'           => $vote
        ]);

        $status = $compilationLike->wasRecentlyCreated ? 'Vote saved' : 'Vote changed';

        return back()->with('status', $status);
    }

    public function storeSettings(Compilation $compilation, Request $request)
    {
        $compilation->settings()->updateOrCreate([
            'id'      => $request->post('id'),
            'user_id' => $request->user()->id
        ], [
            'value'   => $request->post('value'),
        ]);

        return response(null, SymfonyResponse::HTTP_OK);
    }

    public function showUserCompilations(int $userId)
    {
        $compilations = $this->compilation->where('user_id', $userId)->get();

        return view('users.compilations', compact('compilations'));
    }
}

resources/views/compilations/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create new compilation</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        <form class="form-horizontal" action="{{ route('compilations.store') }}" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="youtube_url" class="col-md-3">YouTube URL</label>
                                <div class="col-md-9">
                                    <input type="url" class="form-control" id="youtube_url" name="youtube_url">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="title" class="col-md-3">Title</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control" id="title" name="title">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="description" class="col-md-3">Description/Comment</label>
                                <div class="col-md-9">
                                    <textarea name="description" id="description" class="form-control"></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-3">
                                    <label for="playlist">Playlist</label>
                                    <p class="help-block small">Preferred format<br/>[time] - [artist] - [song]</p>
                                </div>

                                <div class="col-md-9">

                                    <div>
                                        <div class="btn-group" role="group" aria-label="Playlist source" style="margin-bottom: 1em;">
                                            <a href="{{ route('compilations.create') }}" class="btn btn-sm {{ $source == "file" ? "btn-info" : "btn-default" }}">File</a>
                                            <a href="{{ route('compilations.create', ['source' => 'text'])  }}" class="btn btn-sm {{ $source == "text" ? "btn-info" : "btn-default" }}">Text</a>
                                        </div>
                                    </div>

                                    <input type="hidden" name="source" id="source" value="{{ $source }}">

                                    @if($source == "text")
                                    <textarea name="playlist" id="playlist" class="form-control"></textarea>
                                    @else
                                    <input type="file" name="playlist" id="playlist">
                                    @endif
                                </div>
                            </div>

                            <div class="form-group" style="margin-top: 2em;">
                                <div class="col-md-9 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Create</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/compilations/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Compilations</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @forelse ($compilations->chunk(2) as $compilationChunk)
                            <div class="row">
                                @foreach($compilationChunk as $compilation)
                                    <div class="col-xs-6">
                                        <div class="thumbnail">
                                            <img src="https://img.youtube.com/vi/{{ $compilation->video_id }}/mqdefault.jpg" alt="Thumbnail of {{ $compilation->title }}">
                                            <div class="caption">
                                                <h4><a href="/compilations/{{$compilation->id}}">{{ $compilation->title }}</a></h4>
                                                <p>{{ $compilation->description }}</p>
                                                <p class="text-muted small">Added by <a href="{{ route('users.show', $compilation->creator) }}">{{ $compilation->creator->name }}.</a></p>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @empty
                            <p>No compilations. <a href="{{ route('compilations.create') }}">You can create one</a></p>
                        @endforelse
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/compilations/show.blade.php
@extends('layouts.app')

@section('header')
    <meta property="og:image" content="https://img.youtube.com/vi/{{ $compilation->id }}/maxresdefault.jpg">
    <meta property="og:title" content="{{ $compilation->title }}">
    @if ($compilation->description)
    <meta property="og:description" content="{{ $compilation->description }}">
    @endif
    <meta property="og:url" content="{{ request()->url() }}">
    <meta name="twitter:card" content="summary_large_image">

    <style>
        .videowrapper {
            position: relative;
            padding-bottom: 56.25%; /* 16:9 */
            padding-top: 25px;
            height: 0;
        }
        .videowrapper iframe {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }
        #playlist {
            margin-top: 1em;
        }
        .song-title {
            cursor: pointer;
        }
        .success .song-title {
            font-weight: bold;
        }
        form {
            display: inline;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {{ $compilation->title }}
                        <small class="pull-right text-muted" style="margin-top: 2px;">added by <a href="{{ route('users.show', $compilation->creator) }}">{{ $compilation->creator->name }}</a></small>
                    </div>

                    <div class="panel-body">
                        @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                        @endif

                        @if($compilation->description)
                        <p class="lead">{{ $compilation->description }}</p>
                        <hr>
                        @endif

                        <div class="videowrapper">
                            <iframe id="player" width="560" height="315" src="https://www.youtube.com/embed/{{ $compilation->video_id }}?enablejsapi=1" frameborder="0" allowfullscreen></iframe>
                        </div>

                        <div class="clearfix" style="margin-top: 1em;">
                            <div class="btn-group btn-group-sm pull-left">
                                <button id="shuffle" title="Shuffle" data-value="{{ $settings->get(\App\CompilationSettings::SHUFFLE) }}" class="btn {{ chooseClass($settings->get(\App\CompilationSettings::SHUFFLE), 'btn-info', 'btn-default') }}"><i class="fa fa-random"></i></button>
                                <button id="repeat" title="Repeat" data-value="{{ $settings->get(\App\CompilationSettings::REPEAT) }}" class="btn {{ chooseClass($settings->get(\App\CompilationSettings::REPEAT), 'btn-info', 'btn-default') }}"><i class="fa fa-repeat"></i></button>
                            </div>
                            <div class="pull-right">
                                <div class="btn-group btn-group-sm">
                                    <button title="Like" class="btn {{ chooseClass($vote === true, 'btn-info', 'btn-default') }}">{{ $likes }} <i class="fa fa-thumbs-up"></i></button>
                                    <button title="Dislike" class="btn {{ chooseClass($vote === false, 'btn-info', 'btn-default') }}">{{ $dislikes }} <i class="fa fa-thumbs-down"></i></button>
                                </div>
                                <button title="Share" class="btn btn-sm btn-default"><i class="fa fa-share-alt"></i></button>
                            </div>
                        </div>

                        <hr>

                        <h3 class="text-center">Playlist</h3>

                        <table class="table table-striped" id="playlist">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Starts At</th>
                                <th>Song</th>
                                <th>
                                    <input id="selectall" type="checkbox" title="Select all" />
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td colspan="4">
                                    <p class="text-center text-muted"><em>Please wait while fetching playlist...</em></p>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('footer')
    <script defer src="https://www.youtube.com/iframe_api"></script>
    <script defer src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/lodash@4.17.4/lodash.min.js"></script>
    <script defer src="{{ asset('js/compilation.js') }}"></script>
@endsection